from tkinter import *

myroot = Tk()
myroot.geometry('200x300')
myb4 = Button(myroot, text = 'PYTHON', relief = 'raised', cursor = 'circle',bd = 2)
myb4.pack()
myb5 = Button(myroot, text = 'PYTHON', relief = 'raised', cursor = 'clock',bd = 2)
myb5.pack()
myb6 = Button(myroot, text = 'PYTHON', relief = 'raised',  cursor = 'cross',bd = 2)
myb6.pack()
myb7 = Button(myroot, text = 'PYTHON', relief = 'raised',  cursor = 'plus',bd = 2)
myb7.pack()
myb8 = Button(myroot, text = 'PYTHON', relief = 'raised',  cursor = 'tcross',bd = 2)
myb8.pack()
myb9 = Button(myroot, text = 'PYTHON', relief = 'raised',  cursor = 'star',bd = 2)
myb9.pack()
myb10 = Button(myroot, text = 'PYTHON', relief = 'raised',  cursor = 'spider',bd = 2)
myb10.pack()
myb11 = Button(myroot, text = 'PYTHON', relief = 'raised',  cursor = 'watch',bd = 2)
myb11.pack()
myroot.mainloop()
