from tkinter import *

myroot = Tk()
myroot.geometry('200x300')
myb1 = Button(myroot, text = 'PYTHON', relief = 'sunken', bitmap = 'error',bd = 2)
myb1.pack()
myb2 = Button(myroot, text = 'PYTHON', relief = 'sunken', bitmap = 'gray12',bd = 2)
myb2.pack()
myb3 = Button(myroot, text = 'PYTHON', relief = 'sunken', bitmap = 'gray25',bd = 2)
myb3.pack()
myb4 = Button(myroot, text = 'PYTHON', relief = 'sunken', bitmap = 'gray50',bd = 2)
myb4.pack()
myb5 = Button(myroot, text = 'PYTHON', relief = 'sunken', bitmap = 'gray75',bd = 2)
myb5.pack()
myb6 = Button(myroot, text = 'PYTHON', relief = 'sunken', bitmap = 'info',bd = 2)
myb6.pack()
myb7 = Button(myroot, text = 'PYTHON', relief = 'sunken', bitmap = 'hourglass',bd = 2)
myb7.pack()
myb8 = Button(myroot, text = 'PYTHON', relief = 'sunken', bitmap = 'warning',bd = 2)
myb8.pack()
myb9 = Button(myroot, text = 'PYTHON', relief = 'sunken', bitmap = 'question',bd = 2)
myb9.pack()
myb10 = Button(myroot, text = 'PYTHON', relief = 'sunken', bitmap = 'questhead',bd = 2)
myb10.pack()
myroot.mainloop()
